version: '3.6'
networks:
    ${SONAR_NETWORK:-sonar}: {}

services:
    srv:
        image: sonarqube:lts
        hostname: ${SONAR_HOST:-sonar-server}
        volumes:
            - ${SONAR_HOME:-./var}/data:/opt/sonarqube/data
            - ${SONAR_HOME:-./var}/logs:/opt/sonarqube/logs
            - ${SONAR_HOME:-./var}/extensions:/opt/sonarqube/extensions
        ports:
            - ${SONAR_PORT:-9999}:${SONAR_PORT:-9999}
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
            SONAR_WEB_PORT: ${SONAR_PORT:-9999}
            SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 1
            discovery.type: single-node
        networks:
            - ${SONAR_NETWORK:-sonar}
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - ${SONAR_HOME:-./var}/db:/var/lib/postgresql/data 
        networks:
            - ${SONAR_NETWORK:-sonar}
